DROP SEQUENCE SEQ_GEOMID;
CREATE TEMPORARY SEQUENCE SEQ_GEOMID;
-- CREATE SEQUENCE SEQ_GEOMID CYCLE;
TRUNCATE TABLE USERGEOM_GEOMETRY CASCADE;
DROP TABLE USERGEOM_GEOMETRY;
CREATE TABLE USERGEOM_GEOMETRY (
-- CREATE TEMPORARY TABLE USERGEOM_GEOMETRY (
		  ElementID varchar(22) NOT NULL,
		  geomtype geom3dtype,
		  Geometry jsonb NOT NULL, 
		  BODY_MAJOR_AXIS1 point3d,
		  BODY_MAJOR_AXIS2 point3d,
		  BODY_MAJOR_AXIS3 point3d,
		  BODY_MAJOR_AXIS_CENTROID point3d,
		  PRIMARY KEY (ElementID)
-- ) ON COMMIT PRESERVE ROWS;
);

TRUNCATE TABLE USERGEOM_TOPO_FACE CASCADE;
DROP TABLE USERGEOM_TOPO_FACE;
CREATE TABLE USERGEOM_TOPO_FACE (
-- CREATE TEMPORARY TABLE USERGEOM_TOPO_FACE (
		  ElementID varchar(22) NOT NULL,
		  ID	varchar(22) NOT NULL,
		  Type varchar(8) NOT NULL,
		  Polygon jsonb NOT NULL,
		  Normal point3d NOT NULL,
		  AngleFromNorth double precision,
		  Centroid point3d NOT NULL,
		  Orientation varchar(8),
		  Area double precision
-- ) ON COMMIT PRESERVE ROWS;
);
CREATE INDEX I_USERG_TOPOF_GID ON USERGEOM_TOPO_FACE (ElementID);

TRUNCATE TABLE USERGEOM_SPATIALINDEX CASCADE;
DROP TABLE USERGEOM_SPATIALINDEX;
CREATE TABLE USERGEOM_SPATIALINDEX (
-- CREATE TEMPORARY TABLE USERGEOM_SPATIALINDEX (
		  ElementID varchar(22) NOT NULL, 
		  CellID varchar(12) NOT NULL, 
		  CellType integer NOT NULL,
		  XMINBOUND integer,
		  YMINBOUND integer,
		  ZMINBOUND integer,
		  XMAXBOUND integer,
		  YMAXBOUND integer,
		  ZMAXBOUND integer,
		  DEPTH integer,
		  PRIMARY KEY (ElementID, CellID)
-- ) ON COMMIT PRESERVE ROWS;
);
CREATE INDEX I_USERG_SPIDX_CID ON USERGEOM_SPATIALINDEX(CELLID); 
CREATE INDEX IXMIN_SPIDX_UGEOM ON USERGEOM_SPATIALINDEX(XMINBOUND);
CREATE INDEX IYMIN_SPIDX_UGEOM ON USERGEOM_SPATIALINDEX(YMINBOUND);
CREATE INDEX IZMIN_SPIDX_UGEOM ON USERGEOM_SPATIALINDEX(ZMINBOUND);
CREATE INDEX IXMAX_SPIDX_UGEOM ON USERGEOM_SPATIALINDEX(XMAXBOUND);
CREATE INDEX IYMAX_SPIDX_UGEOM ON USERGEOM_SPATIALINDEX(YMAXBOUND);
CREATE INDEX IZMAX_SPIDX_UGEOM ON USERGEOM_SPATIALINDEX(ZMAXBOUND);
-- CREATE TEMPORARY TABLE BIMRL_OUTPUT_DETAILS
-- (
-- 		  ELEMENTID varchar(22) NOT NULL,
-- 		  OUTPUTDETAILS varchar(22)
-- ) ON COMMIT PRESERVE ROWS;
-- CREATE INDEX I_OUTDET_EID ON BIMRL_OUTPUT_DETAILS(ELEMENTID);

TRUNCATE TABLE CELLTREEDETTMP CASCADE;
DROP TABLE CELLTREEDETTMP;
CREATE TABLE CELLTREEDETTMP (
		  CELLID varchar(12) NOT NULL,
		  ELEMENTID varchar(22) NOT NULL
);
CREATE INDEX I_CTTMP_CELLID ON CELLTREEDETTMP (CELLID);
CREATE INDEX I_CTTMP_CELLEID ON CELLTREEDETTMP (CELLID, ELEMENTID);

TRUNCATE TABLE BIMRLQUERYTEMP CASCADE;
DROP TABLE BIMRLQUERYTEMP;
CREATE TABLE BIMRLQUERYTEMP (
		  ID1 varchar(22)
);
